name: TextTransformer
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
          cache: maven
          
      - name: Delete previous jars
        run: mvn clean
          
      - name: Validate, build and run tests
        run: mvn --batch-mode --update-snapshots verify
        
      - run: mvn package
      
      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging
