name: TextTransformer
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
          cache: maven
          
      - name: Delete previous jars
        run: mvn clean install
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
         name: TextTransformer
         path: TextTransformer/target/**
   
      - name: Validate, build and run tests
        run: mvn --batch-mode --update-snapshots verify
        
      

